#baseURL = "https://mircot.github.io/"
baseURL = ""
languageCode = "en"
DefaultContentLanguage = "en"
title = "My personal website"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
publishDir = "../docs"

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "I'm Mirco Tracolli"
author = "Mirco Tracolli"
description = "So much time and so little to do. Wait a minute. Strike that! Reverse it!"
profilePicture = "/images/profile.jpg"
keywords = ""
favicon = "/favicons/"
customCss = []
customJs = []
mainSections = ["post"]
# images = ["images/site-feature-image.png"]

# Google Site Verification
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/mirco-tracolli-66b322155"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/MircoT"


# [[params.socialIcons]]
# icon = "fas fa-envelope"
# title = "e-mail"
# url = "mailto:mail@alexbilz.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
